modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/PlayerRevive/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="playerrevive"
    logoFile="playerrevive.png"
    version="2.0.20"
    displayName="PlayerRevive"
    displayURL="https://modrinth.com/mod/playerrevive"
    authors="CreativeMD"
    description='''Help your friends in need and revive them.'''

[[dependencies.playerrevive]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerrevive]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerrevive]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.5"

